# Generated by Django 2.1.5 on 2019-04-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrugName', models.TextField()),
                ('isOpioid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Perscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorID', models.IntegerField()),
                ('Fname', models.TextField()),
                ('Lname', models.TextField()),
                ('Gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female)')], db_index=True, default='M')),
                ('State', models.TextField()),
                ('Credentials', models.TextField()),
                ('Specialty', models.TextField()),
                ('OpioidPerscriber', models.BooleanField()),
                ('TotalPerscriptions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuanityPerscribed', models.IntegerField()),
                ('Drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perscriptions.Drug')),
                ('Perscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perscriptions.Perscriber')),
            ],
        ),
    ]
