# Generated by Django 2.1.5 on 2019-04-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perscriptions', '0002_auto_20190408_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perscriptions',
            name='QuanityPerscribed',
            field=models.IntegerField(),
        ),
    ]
