# Generated by Django 2.1.5 on 2019-04-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perscriptions', '0004_auto_20190409_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriber',
            name='TotalPrescriptions',
            field=models.IntegerField(blank=True),
        ),
    ]
