# Generated by Django 2.1.5 on 2019-04-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perscriptions', '0005_auto_20190409_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriber',
            name='Credentials',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='DoctorID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='Fname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female)')], db_index=True, default='M', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='Lname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='Specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriber',
            name='State',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
