# Generated by Django 2.1.5 on 2019-04-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perscriptions', '0006_auto_20190409_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriber',
            name='DoctorID',
            field=models.IntegerField(),
        ),
    ]
