# Generated by Django 2.1.5 on 2019-04-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perscriptions', '0007_auto_20190409_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriber',
            name='TotalPrescriptions',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
